document.write('<link rel="stylesheet" type="text/css" href="'+CopyRightcss+'">');

eval(function(p,a,c,k,e,d){e=function(c){return(c<a?"":e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)d[e(c)]=k[c]||e(c);k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1;};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p;}('0 9=\'1://a.b-6.2/7/\';0 8=\'1://3.4.2/f.5\';0 g=\'1://3.4.2/h.5\';0 d=\'e\';0 c=\'1://3.4.2\';',18,18,
'var|http|cn|www|ck61|png|china|copyright|hao123|logoPath|static|sdg|hao123http|logotit|传奇高端网站设计制作|6lu_org_bq|hao123logo|6lu_org_logo|hao123logo|6lu_org_logo'.split('|'),0,{}))

var _sdgCopyrightLink = '#';
var _sdgCopyrightHtml = '<div id=\"header\" class=\"clearfix\">  <div class=\"warp\">    <a href=\"javascript:void(0);\" class=\"fl\"><img src=\"images/bomlogo.png\"></a>  <div id=\"demo\" ><div id=\"demo1\"> <marquee direction=\"left\" scrollamount=\"9\"> 【神话·大极品】——  敬请请广大骨灰玩家品鉴！！</marquee> </div>  <div id=\"demo2\"></div>  </div>  <script type=\"text/javascript\" src=\"js/gund.js\"> </script>   <div class=\"ban\"><a href=\"+ hao123http\" target=\"_blank\" title=\"+ logotit\" ><img src=\"+ hao123logo\"   width=\"50px\" height=\"50px\"></a></div>  </div></div><div id=\"Version\" ><div class=\"hao123\"><img src=\"+hao123\"></div><div id=\"Flash\"><object width=\"100%\" height=\"100%\" codebase=\"/download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0\" classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\"><param value=\"Copytop/flash/banner.swf\" name=\"movie\"><param value=\"transparent\" name=\"wmode\"> <param value=\"true\" name=\"loop\"> <param value=\"high\" name=\"quality\"> <embed width=\"100%\" height=\"100%\" pluginspage=\"/www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" swliveconnect=\"FALSE\" quality=\"high\" wmode=\"transparent\" loop=\"true\" src=\"Copytop/flash/banner.swf\"></embed></object></div><div id=\"Header\"><img src=\"Copytop/images/bg_01.jpg\" width=\"1920\"><img src=\"Copytop/images/bg_02.jpg\" width=\"1920\"><img src=\"Copytop/images/bg_03.jpg\" width=\"1920\"><img src=\"Copytop/images/bg_04.jpg\" width=\"1920\"><img src=\"Copytop/images/bg_05.jpg\" width=\"1920\"><img src=\"Copytop/images/bg_06.jpg\" width=\"1920\"></div></div>';

document.write(_sdgCopyrightHtml);

